"use strict";

const fs = require('fs-extra'),
	  async = require("async"),
	  webpack = require('webpack'),
	  path = require('path');
	
fs.removeSync('./dist');

var basePath = path.resolve('./specWebpack/src/');

var webpackConfig = [
	require(basePath + '/resource-dev/webpack.config.js'), 		// dev environment
	require(basePath + '/resource-inline-1/webpack.config.js'),	// inline without compression
	require(basePath + '/resource-inline-2/webpack.config.js'),	// inline with compression
	require(basePath + '/resource-md5-1/webpack.config.js'),		// md5 with compression / index chunk before react
	require(basePath + '/resource-md5-2/webpack.config.js'),	    // md5 without compression  / react chunk before index
	require(basePath + '/resource-favico/webpack.config.js'), 	// generate favicon
	require(basePath + '/resource-common-1/webpack.config.js'), 	// common chunk generated by webpack
	require(basePath + '/resource-copy-plugin-1/webpack.config.js'), //  usage with copy-webpack-plugin
	require(basePath + '/resource-copy-plugin-2/webpack.config.js'), //  usage with copy-webpack-plugin
	require(basePath + '/resource-external-1/webpack.config.js'), //  external resource
];

async.filter(webpackConfig, function(configPath, callback) {
	let compiler = webpack(configPath);
	compiler.run(function(err, stats) {
	    callback(err, stats);
	});
}, function(err, results){
    if (!err) {
    	// console.log(results);
    }
    else {
    	console.log(err);
    }
});

